### ISSUE TITLE
Documents with a Field Called Timestamp are having the value set to 1970-01-01T00:00:00Z

### ISSUE THREAD

**Issue by MitchSteed** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#10]
If I create a document like this: 

var c = new JObject
                {
                    ["partitionKey"] = "abc",
                    ["id"] = "abc",
                    ["Timestamp"] = "ABC"
                };

And insert it using DocDB SDK I see this document successfully inserted into the collection: 

{
    "partitionKey": "abc",
    "id": "abc",
    "Timestamp": "ABC",
    "_rid": "EMoXAJusIQABAAAAAAAAAA==",
    "_self": "dbs/EMoXAA==/colls/EMoXAJusIQA=/docs/EMoXAJusIQABAAAAAAAAAA==/",
    "_etag": "\"00007308-0000-0000-0000-5b0efa2c0000\"",
    "_attachments": "attachments/",
    "_ts": 1527708204
}

However if I insert the same document into the same collection but using the BulkExecutor library it changes the Timestamp field: 

{
    "id": "abc",
    "_rid": "EMoXAJusIQACAAAAAAAAAA==",
    "_self": "dbs/EMoXAA==/colls/EMoXAJusIQA=/docs/EMoXAJusIQACAAAAAAAAAA==/",
    "_etag": "\"00007208-0000-0000-0000-5b0ef9f90000\"",
    "partitionKey": "abc",
    "Timestamp": "1970-01-01T00:00:00Z", 
    "_attachments": "attachments/",
    "_ts": 1527708153
}

I haven’t found any documentation that suggests Timestamp is a reserved keyword as _ts already fulfills that purpose. 

The capitalization does matter. Using "TimeStamp" for example is fine, just "Timestamp" has this issue. 

We have reported this issue to the team already, but are putting it here so we can have better visibility if a fix is ever made.

**Comment by abinav2307** [comment]
Hello Mitch, apologies for the delay in responding. 

We have attempted to reproduce this issue with the latest version of the Bulk Executor and we do not see the issue described above. The Timestamp field is unchanged after being ingested through the BulkExecutor.

Can you please give this another try with the latest version (1.4.1) of the BulkExecutor and also read the document with version 2.1.3 of the SDK or above?
