### ISSUE TITLE
More Power? 

### ISSUE THREAD

**Issue by Wauna** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#11]
Hi There, Thank you for putting out the Bulk Executor.. I'm trying hard to get lots of data pushed to Cosmos, but it's proving painful.   I have 3 million records to push in all from SQL Server on-prem to Cosmos. My initial push of 18,000 records is taking forever.  I have allocated the collection to be 1000 RU's. I'm only getting between 2 and 100 RU's while trying to use Bulk Executor.  

Data payload is about 1 KB per record.   I pull all 18k records then loop through them pulling off a subset (batch) and send in batches to Cosmos using bulk Executor.  
 I've tried batches of 10,20, 100 and 1000.  I'm looking for any way to get more throughput. 

```
                //get a new batch
                List<string> batch = new List<string>();
                batch.AddRange(distList.GetRange(iCurrent, iGrab));
                int x = batchNumber;
                tasks.Add(Task.Run(async () => {
                    await SendBulkImportAsync(batch,x,bulkExecutor);
                }));

                batchNumber++;
                
                iCurrent += iGrab;

                await Task.WhenAll(tasks); // wait
                tasks.Clear();

```

and in SendBulkImportAsync: 

```

            Trace.TraceInformation(String.Format("Executing bulk import for batch {0}", iBatch));
            do
            {

                try
                {
                    bulkImportResponse = await bulkExecutor.BulkImportAsync(
                    documents: docs,
                    enableUpsert: false,
                    disableAutomaticIdGeneration: true,
                    maxConcurrencyPerPartitionKeyRange: null,
                    maxInMemorySortingBatchSize: null,
                    cancellationToken: token);
                }
                catch (DocumentClientException de)
                {
                    Trace.TraceError("Document client exception: {0}", de);

                }
                catch (Exception e)
                {
                    Trace.TraceError("Document client exception: {0}", e);

                }

            } while (bulkImportResponse.NumberOfDocumentsImported < docs.Count);
```

I am seeing:   10 documents inserted @0 writes/s,  2 RU/s in 42 sec

Any advice?

**Comment by abinav2307** [comment]
Hello @Wauna, sincere apologies for the delay in getting back to you. This is certainly not expected and you should be seeing significantly better performance than this.

If you are still available to chat about this issue, please feel free to reach out to me directly at abramees@microsoft.com and I'd be happy to walk through your setup and ensure your collection is setup properly to maximize your ingestion using the BulkExecutor.
