### ISSUE TITLE
.NET core support for bulkexecutor

### ISSUE THREAD

**Issue by jayantacs** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#14]
But the Microsoft.Azure.Graphs.BulkImport package only targets net461. Can a netstandard1.6 target be added?

**Comment by olekang** [comment]
This would be needed to be able to use it in Azure Functions v2.

**Comment by rnagpal** [comment]
Please use 2.0.0-preview2 which supports .NET Standard 2.0 which should work with .NET Core applications.
