### ISSUE TITLE
Microsoft.Azure.Documents.InvalidPartitionException: Partition range id 6 does not exist, please retry shortly after re-initializing BulkExecutor instance, 

### ISSUE THREAD

**Issue by AntonioJDios** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#19]
Hi, I am getting this error. The exception is an instance of Microsoft.Azure.Documents.InvalidPartitionException but I cannot catch because is in a protection level. Could you let me know if I cannot do the retry manual or the bulkinsert do automatically by me? 

Thanks in advance.

PS: There is more people with the same issue, https://github.com/Azure-Samples/azure-cosmosdb-graph-bulkexecutor-dotnet-getting-started/issues/4

**Comment by rnagpal** [comment]
This should be fixed by 1.2.0 version of the BulkExecutor library.
