### ISSUE TITLE
.NET Core / Standard

### ISSUE THREAD

**Issue by cyberprune** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#2]
Hello,

Is there are .NET standard version of this library planned? We are currently using the Microsoft.Azure.DocumentDB.Core package, so the bulk update isn't compatible with the Core library.

Thanks

**Comment by Elfocrash** [comment]
You beat me to that one mate.
I am was about to start adding BulkImport support to [Cosmonaut](https://github.com/Elfocrash/Cosmonaut) but it turns out i can't because the `IDocumentClient` of the Core in the .NET Standard version isn't compatible with the BulkExecutor `DocumentClient`

**Comment by c2TheOlin** [comment]
mhm need a dot net core/standard implementation this for it to be useful.

**Comment by galmok** [comment]
Is it possible to create a DocumentClient from .Core version of the library from the .NET version?

**Comment by galmok** [comment]
Is it possible to use the BulkExecutor as it is now in netstandard2.0 project? We tried, but it didn't like the DocumentClient from Microsoft.Azure.DocumentDB.Core (netstandard). Trying to compile results in this error:

The type 'DocumentClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.Documents.Client, Version=1.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

But that assembly is part of Microsoft.Azure.DocumentDB nuget package for .NET framework. :-/

So I guess I can't create a DocumentClient compatible with BulkExecutor in netstandard project.

**Comment by k-miyake** [comment]
I voted for this on the feedback site.
You can vote here. [Feedback Forums: Cosmos DB BulkExecutor for .NET Core
](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/34559206-cosmos-db-bulkexecutor-for-net-core)

**Comment by JonyTek** [comment]
Is there any progress on a core/standard implementation of this?

**Comment by mnmr** [comment]
The .NET SDKs for CosmosDB evolve at glacier speed. Can we please assign more developers to this? 

Having a great database does nothing for developers without proper SDKs to access them.

**Comment by t03apt** [comment]
_IMO Cosmos DB .NET SDK should have a better product owner...
It is so lame that it does not support .NET Core. Also its source code should be open source._

**Comment by rifuller** [comment]
+1  Hitting this too.

**Comment by syedhassaanahmed** [comment]
+1 on this. Is there an ETA for .NET Standard support?

**Comment by tolly1989** [comment]
+1

**Comment by ahoefling** [comment]
+1 This really limits anyone trying to use Azure Functions v2 which is now GA

**Comment by syedhassaanahmed** [comment]
Cosmos DB team released a preview of the .NET Standard version yesterday. https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/2.0.0-preview

**Comment by rnagpal** [comment]
As explained in other thread, we now support .NET Standard 2.0 which should make it work on .NET Core applications. Please use the latest 2.0.0-preview2 release.

**Comment by syedhassaanahmed** [comment]
@RemiBou It was released 2 months ago https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/2.1.0-preview2

**Comment by andremaree** [comment]
> 
> 
> You beat me to that one mate.
> I am was about to start adding BulkImport support to [Cosmonaut](https://github.com/Elfocrash/Cosmonaut) but it turns out i can't because the `IDocumentClient` of the Core in the .NET Standard version isn't compatible with the BulkExecutor `DocumentClient`

So Cosmonaut and Bulk Executor can not be used in the same project? This is what it seems like and is unfortunate this means I can`t use Cosmonaut :(

**Comment by rprasath** [comment]
Is there any timeline for GA of .NetStandard package
https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/2.3.0-preview2

**Comment by paduchuriramesh** [comment]
Any update on release of non preview version of the latest nuget with .net standard support?

**Comment by richardrobberse** [comment]
> Any update on release of non preview version of the latest nuget with .net standard support?

Exactly and next to that, the preview package is not in line with the Microsoft.Azure.Cosmos (3.1.1) package because DocumentClient has been deprecated.

**Comment by Joehannus** [comment]
I'm using the bulk executor to perform updates and for some reason it just exits unexpectedly after the call of BulkUpdateAsync, without any error information. I've used the examples for the .net framework version, presuming that it's basically the same logically, when using .net Core.

Are there any examples out there using .net standard, or core. Including how to configure logging for the bulkexecutor class? Currently I've implemented a .net core console application, using serilog for logging.

**Comment by Joehannus** [comment]
To be more precise - regarding the fact that the console application just exits unexpectedly - I had put a try catch statement around the BulkUpdateAsync statment with two catch blocks, just as in the example (with a DocumentClientException and a Exception respectively),. After the BulkUpdateAsync statment a log statement follows - this is never reached however. Neither is either of the catch blocks reached. The console application just stops.

I've noticed in the output window the following statements b.t.w.:
Sitech.Sahc.Telemetry.BulkIdCorrector Information: 0 : Sorting 100 update items into 1 partition buckets
Sitech.Sahc.Telemetry.BulkIdCorrector Information: 0 : Creating mini batches within each partition bucket
Sitech.Sahc.Telemetry.BulkIdCorrector Information: 0 : partitionRangeId = 0 currentMiniBatchSize = 18252 maxMiniBatchSize = 220201 currentMiniBatchItemCount = 100
Sitech.Sahc.Telemetry.BulkIdCorrector Information: 0 : Beginning bulk update within each partition bucket

Is there a minimum that you can have for a batch. I wanted to test with 100 records first, to see if everything works correctly. But that doesn't explain why the console application would just exit, without reaching one of the catch blocks.

I've also tried to break in the Exception Settings on all Common Language Runtime Exceptions. But nothing happens then either.
