### ISSUE TITLE
Include step to install DocumentDB preview

### ISSUE THREAD

**Issue by joshnoe** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#21]
The latest version of Bulk Executor (Version 1.0.2) targets Microsoft.Azure.DocumentDB 2.0.0, which is in preview.

When you Nuget install Bulk Executor, an older version of Microsoft.Azure.DocumentDB is installed, and the provided sample won't build.

The workaround for now is to force uninstall Microsoft.Azure.DocumentDB and then explicitly install Microsoft.Azure.DocumentDB 2.0.0 Preview.

**Comment by rnagpal** [comment]
This was fixed with 1.1.0 release of the bulk executor
