### ISSUE TITLE
Encountered exception while executing function. Exception = JSRT error 0x30003

### ISSUE THREAD

**Issue by Wauna** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#25]
The .NET Version of the bulk executor stopped working.  Looking for help. Attempt to insert 1 record using bulk executor resulted in this error message. Also tried the same using Data Factory, and got the same message. 

Any help would be GREATLY appreciated!

{ 'errorCode': '2200', 'message': ''Type=Microsoft.Azure.Documents.DocumentClientException,Message=Partition range id 0 | Failed to import mini-batch. Exception was Message: {\\'Errors\\':[\\'**Encountered exception while executing function. Exception = JSRT error 0x30003**\\']}\\r\\nActivityId: 4fd56039-459d-4c6f-9be9-ea7305cae5fe, Request URI: /apps/806df639-a21a-4efb-8e15-02c4a490af46/services/43c0f16f-e82c-4c1c-bca2-602743e971cd/partitions/cd0eb199-3edc-4aa3-aede-7115d20b624d/replicas/131810532074365699p/, RequestStats: , SDK: documentdb-dotnet-sdk/1.21.1 Host/64-bit MicrosoftWindowsNT/6.2.9200.0. Status code was 500\\r\\nActivityId: f5569d5e-3565-4769-9b50-947603b14ef4, documentdb-dotnet-sdk/1.21.1 Host/64-bit MicrosoftWindowsNT/6.2.9200.0,Source=Microsoft.Azure.CosmosDB.BulkImport,''Type=Microsoft.Azure.Documents.InternalServerErrorException,Message=Message: {\\'Errors\\':[\\'Encountered exception while executing function. Exception = JSRT error 0x30003\\']}\\r\\nActivityId: 4fd56039-459d-4c6f-9be9-ea7305cae5fe, Request URI: /apps/806df639-a21a-4efb-8e15-02c4a490af46/services/43c0f16f-e82c-4c1c-bca2-602743e971cd/partitions/cd0eb199-3edc-4aa3-aede-7115d20b624d/replicas/131810532074365699p/, RequestStats: , SDK: documentdb-dotnet-sdk/1.21.1 Host/64-bit MicrosoftWindowsNT/6.2.9200.0,Source=Microsoft.Azure.Documents.Client,'', 'failureType':

**Comment by rnagpal** [comment]
This was fixed with 1.1.1 version of the BulkExecutor release.

**Comment by dsherret** [comment]
@rnagpal did you mean the 1.3.0 release?
