### ISSUE TITLE
Bulk executor for .net core -- is there any way we can user bulk executor in .net core -- Azure function 2.0

### ISSUE THREAD

**Issue by vibhorrastogi87** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#26]
any ways to use bulk executor in azure function V2.0

**Comment by ahoefling** [comment]
I'm looking for Azure Function v2 support as well (.NET Core)

**Comment by rnagpal** [comment]
Please try 2.0.0-preview2 version of teh BulkExecutor for the .NET Core applications.
