### ISSUE TITLE
2.0.0-preview targeting .NET Standard 2.0 instead of 1.6

### ISSUE THREAD

**Issue by Elfocrash** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#29]
First and foremost, thank you for working towards a .NET Standard release. 

I have to ask this question though. Why is the new 2.0.0-preview targeting .NET Standard 2.0 and not .NET Standard 1.6?

None of it's dependencies requires 2.0 and most importantly the `Microsoft.Azure.DocumentDB.Core` doesn't target 2.0 either. It targets .NET Standard 1.6. It looks likes an inconsistency and a limitation that will confuse.

If there is some other reason behind this choice we'd love to know it, if that's something you could share.

Again, thanks for releasing this.

**Comment by rnagpal** [comment]
@Elfocrash : We wanted to see if many people ask for .NET Standard 1.6 or they will prefer .Net Standard 2.0 as that's the latest and greatest, no other reason. All our new Cosmos DB packages like Changefeed Processor and Table that came out within the last year only have .Net Standard 2.0, so we wanted to be consistent. If we see good interest for .Net Standard 1.6 for Bulk Executor, we will provide one.

**Comment by Elfocrash** [comment]
It makes perfect sense and I do agree that preferring .NET STANDARD 2.0 is definitely a step in the right direction.

Thanks @rnagpal!
