### ISSUE TITLE
No BulkDeleteAsync

### ISSUE THREAD

**Issue by JasonBSteele** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#3]
Hi, although there is a Microsoft.Azure.CosmosDB.BulkExecutor.BulkDelete namespace with a couple of classes, there is no BulkDeleteAsync method in the BulkExecutor.

Is this a work in progress, or am I looking in the wrong place to do bulk deletions?

**Comment by alexjamesbrown** [comment]
I also have the same question.

There's a class called `BulkDeleteQuerySpec` but this doesn't appear in any docs?

**Comment by ninhvuonglinh-linhnv** [comment]
I also have the same question. 
Using Version 1.0.1, and found in the class `BulkExecutor` is defined `BulkDeleteAsync`.

**Comment by snowinmars** [comment]
Hi.

I reverse engineered it.

This class uses to build SQL query.
Usual SQL query is like `select * from t where t.id = 1`

`BulkDeleteQuerySpec.RootSymbol` is ' t '
`BulkDeleteQuerySpec.FilterExpression` is ' t.id = 1 '
and so on

So, the right usage of the `BulkDeleteAsync` method is

`

    var querySpec = new BulkDeleteQuerySpec(" t ", " t.id = 1 ", "", null);

    var method = typeof(BulkExecutor).GetMethod("BulkDeleteAsync", BindingFlags.NonPublic | BindingFlags.Instance);

    await ((Task)method.Invoke(bulkExecutor, new object[] { querySpec })).ConfigureAwait(false);
`

P.S. See [here](https://docs.microsoft.com/en-us/azure/cosmos-db/bulk-executor-dot-net) how to get `bulkExecutor`. Btw, to avoid `'Value cannot be null. Parameter name: key'` exception in the bulkExecutor constructor, reread document collection from the server.

**Comment by rnagpal** [comment]
Please use 1.3.0 version of teh BulkExecutor library that supports BulkDeleteAsync API.
