### ISSUE TITLE
Missing documentation for BulkDelete, `query` parameter issue

### ISSUE THREAD

**Issue by jkonecki** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#30]
There is no documentation for BulkDelete API.
I cannot find any information regarding the `query` parameter. 

Providing 
`SELECT * FROM Collection c WHERE c.Partition = 'foo'`
actually deletes ALL documents in the collection instead of only those matching the query provided.

**Comment by rnagpal** [comment]
@jkonecki : We will be hot-fixing this issue this week and add documentation/samples. 
Try using  : SELECT * FROM c WHERE c.Partition = 'foo' to work around this issue until then.

**Comment by communicatorcloud** [comment]
@rnagpal There are still no documentation / samples for BulkDelete API.

**Comment by cgelon** [comment]
The latest package (1.4.0) has changed the parameters of BulkDeleteAsync to be a List<Tuple<string, string>> of PartitionKey and ID (PartitionKey is first and ID of the document is second) and an optional integer of batch delete size. Providing it with a list of tuples should now be pretty straightforward.

Note that this definition is now only on BulkExecutor; it has been mysteriously removed from IBulkExecutor.

**Comment by abinav2307** [comment]
We recently noticed a bug in the query overload for BulkDelete, because of which it was removed in the latest version(s).

Currently, our BulkDelete only supports <Partition key, id> tuples as input.

However, we are working on a fix for the query overload as well and will add a sample as soon as the fix is released.

**Comment by abinav2307** [comment]
Just added a sample for BulkDelete using <PartitionKey, DocumentId> tuples here - https://github.com/Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started
