### ISSUE TITLE
Nuget Warning, should use DocumentDb = 2.1.3, version 2.2.0 was resolved.

### ISSUE THREAD

**Issue by matthewacme** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#32]
Not sure if this is a Nuget issue, or a nuget package issue, or is this an actual hard requirement. I've upgraded to the current release of Microsoft.Azure.DocumentDB v 2.2.0 but the nuget package for teh bulkexecutor is saying it needs to be Microsoft.Azure.DocumentDB v 2.1.3

Severity	Warning	
Code	NU1608	
Description	Detected package version outside of dependency constraint: Microsoft.Azure.CosmosDB.BulkExecutor 1.4.0 requires Microsoft.Azure.DocumentDB (= 2.1.3) but version Microsoft.Azure.DocumentDB 2.2.0 was resolved.

**Comment by rifuller** [comment]
I'm seeing a missing method error in InitializeAsync() when using Microsoft.Azure.DocumentDB.Core 2.2.1 and Microsoft.Azure.DocumentDB.BulkExecutor  2.1.0-preview2.

 `Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync`

I think they're incompatible.

**Comment by rifuller** [comment]
Confirming that using M.Azure.DocumentDB.Core 2.1.3 works when 2.2.0 didn't.

**Comment by matthewacme** [comment]
Month and a Half guys, is anyone actually looking at this stuff?

**Comment by Cephei** [comment]
Is it really necessary that the dependency constraints be so strict in versioning DocumentDB.Core? Would like support for `2.2.1`.

**Comment by abinav2307** [comment]
Hi all,

Apologies for the delay in responding. As @rifuller pointed out, this is a hard dependency in the present version of the BulkExecutor due to internal dependencies.

We are looking to see if some of these internal dependencies can be resolved in subsequent release of the BulkExecutor. 

In addition, we are also working on a batch API which will be internal to our SDK as well, eliminating the need for multiple libraries in the near future.

**Comment by vikhar** [comment]
Is there any further update on this ? We are planning to use Bulk Executor in our application, but the fact that there is a hard dependency on M.Azure.DocumentDB.Core 2.1.3, we are not sure on future prospects on this.

**Comment by matthewacme** [comment]
Based on my experience I would strongly urge you to find another solution until the BulkExecutor team either fixes this hard dependency or open sources the library.

> 
> 
> Is there any further update on this ? We are planning to use Bulk Executor in our application, but the fact that there is a hard dependency on M.Azure.DocumentDB.Core 2.1.3, we are not sure on future prospects on this.

**Comment by vikhar** [comment]
Thanks Matthew, other options are not very clean. I did try to use the Stored Procedure way, but there is a limitation of 2MB max size for the array of docs. We are dealing with pretty big documents and with SPs it is becoming bit of a mess.

Bulk Executor is actually solving these problems and does all the processing internally. Only problem is this hard dependency. if there is any chance of changing this in future, we could still consider this.

Any specific issue you want me be aware of, if we decide to use this.

**Comment by ealsur** [comment]
Just FYI on this thread, checking the Nuget package, the current dependency is 2.5.1 https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/1.8.1
