### ISSUE TITLE
Where's the SRC...?

### ISSUE THREAD

**Issue by anubi** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#34]
I am trying to optimize my solution with this library. I am finding BulkImportAsync is taking a ridiculous amount of memory (2GB memory in utilization when processing just 16MB of data) and I want to step through to see whether my code needs to change, or whether I could contribute optimizations to CosmosDB.BulkExecutor. All I can find is this repo on github though, which just includes examples. Please help!

**Comment by abinav2307** [comment]
Presently, we do not plan to open source the BulkExecutor library as it contains "under the hood" implementation details. In addition, while the library does perform pre-processing steps prior to ingestion, it should not be utilizing 2GB of memory for 16MB of documents. Feel free to reach out to abramees@microsoft.com and I can help walk through your setup.

**Comment by HiroyukiSakoh** [comment]
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/675
