### ISSUE TITLE
How to retry bulk import if it fails or not imported all document in one batch/call.

### ISSUE THREAD

**Issue by AjitBhosale** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#38]
executing bulk import with following configurations - 
1. MaxRetryWaitTimeInSeconds  and MaxRetryAttemptsOnThrottledRequests  set to 0.
2.  Importing document without id, enableUpsert is flase and disableAutomaticIdGeneration is false.
3. code -

  do
            {
              try
             {
                    bulkImportResponse = await bulkExecutor.BulkImportAsync(bulkDocument, false, false);
             }
               catch (Exception e)
                 {
                 // log exception
                }
             }
             while (bulkImportResponse.NumberOfDocumentsImported < bulkDocument.Count());
        
So if it throw any exception during documents insertion(line 5) than it will rollback inserted document internally or not? if not than i require to remove NumberOfDocumentsImported  from bulkDocument before retry with do-while loop?

**Comment by abinav2307** [comment]
If the batch fails, you can simply re-run the BulkImportAsync method with the same batch of documents, but this time, with enableUpsert set to true. 

As a pre-processing step for a scenario such as this, we would also recommend assigning Guids as ids for the documents to avoid duplicates when retrying the batch.
