### ISSUE TITLE
Using this library under Azure Function is not possible

### ISSUE THREAD

**Issue by Gaploid** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#5]
Hi,
Azure functions v1.* is locked on Newtonsoft.Json = 9.0 but this library needs a ver. > 10.0
Azure functions v2. is only support .net core and this library does not compatible with .net core.  

Any ideas how to use bulk executor in Azure functions?

**Comment by leftside** [comment]
I also have the same question. One of our batch processes drops a JSON file into Blob Storage. This extractor would have been ideal to parse the file and put the JSON documents into Cosmos.

**Comment by rnagpal** [comment]
This was fixed in 1.1.0 release of BulkExecutor. Please update to the latest version of the library.
