### ISSUE TITLE
Limit number of RUs consumed

### ISSUE THREAD

**Issue by lfalck** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#51]
Hi!

Is there a way to limit the number of RUs consumed by the Bulk Executor? 

We are inserting or updating around 50 000 documents in under one minute which is great but it consumes 300 000 RUs. This depletes the provisioned throughput and causes subsequent selects to fail. If possible we would like to trade some speed for lower RU usage.

I tried tuning `maxConcurrencyPerPartitionKeyRange` and `ConnectionPolicy.MaxConnectionLimit` but even setting them to 1 did not change the results much,

Thanks!

/Ludvig

**Comment by gorillapower** [comment]
@lfalck did you find a solution to your issue?

**Comment by lfalck** [comment]
@gorillapower not really, we added some logic to minimize unnecessary updates (when there were no changes) and then increased the RUs of the container until we could do the bulk loads without any throttling.

**Comment by lfalck** [comment]
I was able to accomplish what i wanted by tweaking `maxInMemorySortingBatchSize` which is a parameter to `BulkImportAsync` and `BulkUpdateAsync`.
