### ISSUE TITLE
One or more errors occurred. (Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Routing.CollectionRoutingMap> Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync(System.String, Microsoft.Azure.Documents.Routing.CollectionRoutingMap, System.Threading.CancellationToken, Boolean)'.)

### ISSUE THREAD

**Issue by sagar2610** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#58]
Issue is occuring on .NET core 2.2 and I have used all the latest and old packages of bulkexecutor and I am getting error in all.
**BulkExecutor = 2.3.0-preview2
Db.Core = 2.1.3**

One or more errors occurred. (Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Routing.CollectionRoutingMap> Microsoft.Azure.Documents.Routing.PartitionKeyRangeCache.TryLookupAsync(System.String, Microsoft.Azure.Documents.Routing.CollectionRoutingMap, System.Threading.CancellationToken, Boolean)'.)

**Comment by omnoms** [comment]
I have this same issue. It's a copy-paste of the BulkImport example in this repo.

**Comment by topagarwal** [comment]
I am still seeing this with
```
<PackageReference Include="Microsoft.Azure.CosmosDB.BulkExecutor" Version="2.0.0-preview" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.13.1" />
```

**Comment by topagarwal** [comment]
You would need either:

- Microsoft.Azure.DocumentDB 2.13.1 and Microsoft.Azure.CosmosDB.BulkExecutor 1.8.9 if the app is a full framework (net46/net47)
- Microsoft.Azure.DocumentDB.Core 2.13.1 and Microsoft.Azure.CosmosDB.BulkExecutor 2.5.1-preview if the app is a NET Core application

https://github.com/Azure/azure-cosmos-dotnet-v2/issues/653

**Comment by ealsur** [comment]
Please update to the latest available nuget packages both for the SDK and BulkExecutor as the previous comment states.
