### ISSUE TITLE
Could you change the dependency for BulkExecutor from Newtonsoft.Json (>= 10.0.2) to Newtonsoft.Json (>= 9.0.1) ?

### ISSUE THREAD

**Issue by qiuyanghui** [Azure/azure-cosmosdb-bulkexecutor-dotnet-getting-started#6]
I would like to use the BulkExecutor in Azure function
but BulkExecutor requires Newtonsoft.Json (>= 10.0.2) 
while the latest Azure Function for .NET Framework v4.6 requires Newtonsoft.Json (= 9.0.1).

Could you change the dependency for BulkExecutor  from Newtonsoft.Json (>= 10.0.2) to Newtonsoft.Json (>= 9.0.1) ?

Thanks,
Yanghui Qiu

**Comment by k-miyake** [comment]
According to this [Issue](https://github.com/Azure/azure-functions-vs-build-sdk/issues/146), it seems that only 9.0.1 in V1 Functions can be used, so I would like that BulkExecutor's dependency will change.

**Comment by marcelmeijer** [comment]
In our case it is a showstopper.

**Comment by ealsur** [comment]
Newtonsoft.Json dependency has been lowered in the 1.1.1 package.

**Comment by qiuyanghui** [comment]
Thanks, ealsur/Matias.
